---
title: "Dentate Gyrus"
author: "Skim"
date: '2020 6 17 '
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float: false
    code_folding: hide
---

```{r warning=FALSE, message=FALSE}
.libPaths(c("/home/skim/R/usr_lib", .libPaths()))
library(Seurat)
library(ggplot2)
library(gridExtra)
library(grid)
library(ggrepel)
library(DT)
library(biomaRt)
library(dplyr)
library(viridis)
library(tidyr)
source("/data/rajewsky/home/skim/Microglia_Heppner/Codes/DroNc_AD/src/TopGO_scRNA.R")
```

Below is each cluster in Neuronal cell types

Dentate Gyrus = 0, 10  
CA1 = 2, 13, 18, 40  
CA2/3 = 9, 21, 27  
Subiculum = 11, 14, 15, 17, 19, 20  
Inhibitory = 7, 16, 22, 30  
Neurons = 24, 29, 32

```{r warning=FALSE, message=FALSE}
load(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200221_figure1_for_meeting_report_Seurat_object.Robj")
```

```{r warning=FALSE, message=FALSE}
cluster_GO <- function(genesOfInterest, geneUniverse){

geneList <- factor(as.integer(geneUniverse %in% genesOfInterest))
names(geneList) <- geneUniverse

onts = c( "MF", "BP", "CC" )
tab <- as.list(onts)
names(tab) <- onts

for(i in 1:3){

GOdata <- new("topGOdata",
                description = "GOanalysis",
                ontology = onts[i],
                allGenes = geneList,
                annot = annFUN.org,
                mapping = "org.Mm.eg.db",
                ID = "SYMBOL",
                nodeSize = 20)

# export GO ID from BP
if(i == 1){
  allGO_MF <- genesInTerm(GOdata)
}
if(i == 2){
  allGO_BP <- genesInTerm(GOdata)
}

if(i == 3){
  allGO_CC <- genesInTerm(GOdata)
}

res.result1 <- runTest(GOdata, statistic = "fisher", algorithm = "elim")
res.result2 <- runTest(GOdata, statistic = "fisher", algorithm = "classic")


tab[[i]] <- cbind(data.frame(category = onts[i]), GenTable(GOdata, Fisher.elim = res.result1,
                        Fisher.classic = res.result2,
                        orderBy = "Fisher.elim" , topNodes = 30))


}

topGOResults <- plyr::rbind.fill(tab)
topGOResults.df <- as.data.frame(topGOResults)
topGOResults.df$gene_ratio <- topGOResults.df$Significant / topGOResults.df$Annotated

# modification appropriate for plot
topGOResults.df$Fisher.elim <- as.numeric(topGOResults.df$Fisher.elim)
topGOResults.df$Fisher.classic <- as.numeric(topGOResults.df$Fisher.classic)
topGOResults.df$Term <- factor(topGOResults.df$Term, levels = rev(unique(topGOResults.df$Term)))

for(i in 1:30){
 ID <- topGOResults.df$GO.ID[i]
 #print(ID)
 #print(paste(genesOfInterest[genesOfInterest %in% allGO[ID][[1]]], collapse=', ' ))
 topGOResults.df[i, "genes"] <- paste(genesOfInterest[genesOfInterest %in% allGO_MF[ID][[1]]], collapse=', ' )
}
for(i in 31:60){
 ID <- topGOResults.df$GO.ID[i]
 #print(ID)
 #print(paste(genesOfInterest[genesOfInterest %in% allGO[ID][[1]]], collapse=', ' ))
 topGOResults.df[i, "genes"] <- paste(genesOfInterest[genesOfInterest %in% allGO_BP[ID][[1]]], collapse=', ' )
}
for(i in 61:90){
 ID <- topGOResults.df$GO.ID[i]
 #print(ID)
 #print(paste(genesOfInterest[genesOfInterest %in% allGO[ID][[1]]], collapse=', ' ))
 topGOResults.df[i, "genes"] <- paste(genesOfInterest[genesOfInterest %in% allGO_CC[ID][[1]]], collapse=', ' )
}

return(topGOResults.df)
}

# ggplot function
scRNA_TopGO_plot2 <- function(topGOResults.df){

topGOResults.df$Fisher.elim <- as.numeric(topGOResults.df$Fisher.elim)
topGOResults.df$Fisher.elim <- -log10(topGOResults.df$Fisher.elim)
topGOResults.df$Term <- factor(topGOResults.df$Term, levels = rev(unique(topGOResults.df$Term)))

ggplot(topGOResults.df, aes(x=gene_ratio,
               y=Term,
               colour=Fisher.elim,
               size=Significant)) +
        geom_point() +
        expand_limits(x=0) +
        labs(x="gene ratio", y="GO term", colour="-log10(p-value)", size="Significant") +
  theme_minimal() + theme(axis.text = element_text(size = 10))

}
```

### 1. Dentate Gyrus overview

```{r warning=FALSE, message=FALSE}
data9set_DG.SO <- subset(data9set_cleaned.SO, subset = seurat_clusters %in% c(0, 10))

```

```{r warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5}
plot.data <- data9set_cleaned.SO@meta.data %>%
    dplyr::select(sample, gemgroup, cluster = seurat_clusters) %>%
    mutate(cluster = cluster) %>%
    group_by(gemgroup, cluster, sample) %>%
  summarise(count = n()) %>%
  group_by(gemgroup) %>%
    mutate(gemgroup_total = sum(count)) %>%
    mutate(cell_prop = count / gemgroup_total)

ggplot(plot.data[plot.data$cluster %in% c(0, 10),], aes(x=cluster, y=cell_prop, fill=sample)) +
  geom_boxplot(position=position_dodge(1)) + ylim(c(0, 0.3))
```

```{r  warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5}
# Idents(data9set_DG.SO) <- data9set_DG.SO$seurat_clusters
# 
# c0.markers <- FindMarkers(data9set_DG.SO, ident.1 = "0", ident.2 = c("10"), min.pct = 0.05)
# write.csv(c0.markers, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_cluster0_markers.csv")
c0.markers <- read.csv(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_cluster0_markers.csv", row.names = 1)

# c10.markers <- FindMarkers(data9set_DG.SO, ident.1 = "10", ident.2 = c("0"), min.pct = 0.05)
# write.csv(c10.markers, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_cluster10_markers.csv")
c10.markers <- read.csv(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_cluster10_markers.csv", row.names = 1)

```

```{r  warning=FALSE, message=FALSE, fig.width=15, fig.height = 5}
DimPlot(data9set_DG.SO, split.by = "sample", group.by = "seurat_clusters") + xlim(c(-25, -10)) + ylim(c(-5, 10))
```

#### 1-1. Cluster 0

```{r warning=FALSE, message=FALSE, fig.width= 8, fig.height= 7.5}
f1 <- FeaturePlot(data9set_DG.SO, features = "Pde4d") + xlim(c(-25, -10)) + ylim(c(-5, 10))
f2 <- FeaturePlot(data9set_DG.SO, features = "Fstl4") + xlim(c(-25, -10)) + ylim(c(-5, 10))
f3 <- FeaturePlot(data9set_DG.SO, features = "Clmp") + xlim(c(-25, -10)) + ylim(c(-5, 10))
f4 <- FeaturePlot(data9set_DG.SO, features = "Unc5d") + xlim(c(-25, -10)) + ylim(c(-5, 10))

grid.arrange(f1, f2, f3, f4, ncol = 2)
```

I lower the gene of interest condition from 0.5 to 0.4 in cluster 0

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 5}
# # background genes
# geneUniverse <- rownames(data9set_DG.SO@assays$RNA@counts[rowSums(data9set_DG.SO@assays$RNA@counts) > 0, ]) %>% as.character
# 
# genesOfInterest <- as.character(rownames(c0.markers[which(c0.markers$p_val_adj < 0.01 & c0.markers$avg_logFC > 0.4 & c0.markers$pct.2 < 0.4), ]))
# 
# topGOResults.df <- cluster_GO(genesOfInterest, geneUniverse)
# #
# write.csv(topGOResults.df, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_GO_cluster0.csv")

topGOResults.df <- read.csv(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_GO_cluster0.csv", row.names = 1)

datatable(topGOResults.df, options = list(pageLength = 5, dom = 'tip'))
```

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 7}
topGOResults_MF.df <- topGOResults.df[which(topGOResults.df$category == "MF" & topGOResults.df$Annotated < 1000 & topGOResults.df$Annotated > 30), ][c(1:15), ]
g1 <- scRNA_TopGO_plot2(topGOResults_MF.df)
g1 <- g1 + ggtitle("Molecular function")

topGOResults_BP.df <- topGOResults.df[which(topGOResults.df$category == "BP" & topGOResults.df$Annotated < 1000 & topGOResults.df$Annotated > 30), ][c(1:15), ]
g2 <- scRNA_TopGO_plot2(topGOResults_BP.df)
g2 <- g2 + ggtitle("Biological process")

grid.arrange(g1, g2, ncol = 2)
```

#### 1-2. Cluster 10

```{r warning=FALSE, message=FALSE, fig.width= 8, fig.height= 7.5}
f1 <- FeaturePlot(data9set_DG.SO, features = "Sgcz") + xlim(c(-25, -10)) + ylim(c(-5, 10))
f2 <- FeaturePlot(data9set_DG.SO, features = "Cntn4") + xlim(c(-25, -10)) + ylim(c(-5, 10))
f3 <- FeaturePlot(data9set_DG.SO, features = "Tenm4") + xlim(c(-25, -10)) + ylim(c(-5, 10))
f4 <- FeaturePlot(data9set_DG.SO, features = "Pde1a") + xlim(c(-25, -10)) + ylim(c(-5, 10))

grid.arrange(f1, f2, f3, f4, ncol = 2)
```

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 5}
# # background genes
# geneUniverse <- rownames(data9set_DG.SO@assays$RNA@counts[rowSums(data9set_DG.SO@assays$RNA@counts) > 0, ]) %>% as.character
# 
# genesOfInterest <- as.character(rownames(c10.markers[which(c10.markers$p_val_adj < 0.01 & c10.markers$avg_logFC > 0.5 & c10.markers$pct.2 < 0.5), ]))
# 
# topGOResults.df <- cluster_GO(genesOfInterest, geneUniverse)
# # #
# write.csv(topGOResults.df, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_GO_cluster10.csv")

topGOResults.df <- read.csv(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_GO_cluster10.csv", row.names = 1)

datatable(topGOResults.df, options = list(pageLength = 5, dom = 'tip'))
```

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 7}
topGOResults_MF.df <- topGOResults.df[which(topGOResults.df$category == "MF" & topGOResults.df$Annotated < 1000 & topGOResults.df$Annotated > 30), ][c(1:15), ]
g1 <- scRNA_TopGO_plot2(topGOResults_MF.df)
g1 <- g1 + ggtitle("Molecular function")

topGOResults_BP.df <- topGOResults.df[which(topGOResults.df$category == "BP" & topGOResults.df$Annotated < 1000 & topGOResults.df$Annotated > 30), ][c(1:15), ]
g2 <- scRNA_TopGO_plot2(topGOResults_BP.df)
g2 <- g2 + ggtitle("Biological process")

grid.arrange(g1, g2, ncol = 2)
```

### 2. DE in Dentate Gyrus neurons

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 7}

# DG_DE_AD_ADp40KO <- FindMarkers(data9set_DG.SO, ident.1 = "AD", ident.2 = "ADp40KO", group.by = "sample", min.pct = 0.01, logfc.threshold = 0.01)
# 
# write.csv(DG_DE_AD_ADp40KO, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_DE_AD_ADp40KO.csv")

DG_DE_AD_ADp40KO <- read.csv(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_DE_AD_ADp40KO.csv")


DG_DE_AD_ADp40KO2 <- DG_DE_AD_ADp40KO[abs(DG_DE_AD_ADp40KO$avg_logFC) > 0.1, ]
# remove Ttr
DG_DE_AD_ADp40KO2 <- DG_DE_AD_ADp40KO2[DG_DE_AD_ADp40KO2$X != "Ttr", ]

# only logFC > 0.1
DG_DE_AD_ADp40KO_padj <- DG_DE_AD_ADp40KO[abs(DG_DE_AD_ADp40KO$avg_logFC) > 0.1, ]
# remove Ttr
DG_DE_AD_ADp40KO_padj <- DG_DE_AD_ADp40KO_padj[DG_DE_AD_ADp40KO_padj$X != "Ttr", ]

DG_DE_AD_ADp40KO_padj <- DG_DE_AD_ADp40KO_padj[which(DG_DE_AD_ADp40KO_padj$p_val_adj < 0.05), ]

datatable(DG_DE_AD_ADp40KO_padj, options = list(pageLength = 5, dom = 'tip'))
```

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 5}
# genesOfInterest <- DG_DE_AD_ADp40KO_padj[DG_DE_AD_ADp40KO_padj$avg_logFC > 0, ]$X %>% as.character
# 
# 
# 
# topGOResults.df <- cluster_GO(genesOfInterest, geneUniverse)
# 
# write.csv(topGOResults.df, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_GO_AD_ADp40KO_UP.csv")

topGOResults.df <- read.csv(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_GO_AD_ADp40KO_UP.csv", row.names = 1)

datatable(topGOResults.df, options = list(pageLength = 5, dom = 'tip'))
```

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 7}
topGOResults_MF.df <- topGOResults.df[which(topGOResults.df$category == "MF" & topGOResults.df$Annotated < 1000 & topGOResults.df$Annotated > 30), ][c(1:15), ]
g1 <- scRNA_TopGO_plot2(topGOResults_MF.df)
g1 <- g1 + ggtitle("Molecular function")

topGOResults_BP.df <- topGOResults.df[which(topGOResults.df$category == "BP" & topGOResults.df$Annotated < 1000 & topGOResults.df$Annotated > 30), ][c(1:15), ]
g2 <- scRNA_TopGO_plot2(topGOResults_BP.df)
g2 <- g2 + ggtitle("Biological process")

grid.arrange(g1, g2, ncol = 2)
```

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 5}
# genesOfInterest <- DG_DE_AD_ADp40KO_padj[DG_DE_AD_ADp40KO_padj$avg_logFC < 0, ]$X %>% as.character
# 
# topGOResults.df <- cluster_GO(genesOfInterest, geneUniverse)
# 
# write.csv(topGOResults.df, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_GO_AD_ADp40KO_DOWN.csv")

topGOResults.df <- read.csv(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200617_Dentate_Gyrus_neurons_analysis_GO_AD_ADp40KO_DOWN.csv", row.names = 1)

datatable(topGOResults.df, options = list(pageLength = 5, dom = 'tip'))
```

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height= 7}
topGOResults_MF.df <- topGOResults.df[which(topGOResults.df$category == "MF" & topGOResults.df$Annotated < 1000 & topGOResults.df$Annotated > 30), ][c(1:15), ]
g1 <- scRNA_TopGO_plot2(topGOResults_MF.df)
g1 <- g1 + ggtitle("Molecular function")

topGOResults_BP.df <- topGOResults.df[which(topGOResults.df$category == "BP" & topGOResults.df$Annotated < 1000 & topGOResults.df$Annotated > 30), ][c(1:15), ]
g2 <- scRNA_TopGO_plot2(topGOResults_BP.df)
g2 <- g2 + ggtitle("Biological process")

grid.arrange(g1, g2, ncol = 2)
```

### 3. DE by clustter

#### 3-1. DE cluster 0

```{r warning=FALSE, message=FALSE}
c0_DE_AD_ADp40KO <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/20200117_Clustering_DE_by_MAST_each_Cluster_0ADp40KO_AD_corrected.csv")

# reverse logFC2
c0_DE_AD_ADp40KO$avg_logFC <- c0_DE_AD_ADp40KO$avg_logFC * -1

c0_DE_AD_ADp40KO2 <- c0_DE_AD_ADp40KO[abs(c0_DE_AD_ADp40KO$avg_logFC) > 0.1, ]
# remove Ttr
c0_DE_AD_ADp40KO2 <- c0_DE_AD_ADp40KO2[c0_DE_AD_ADp40KO2$X != "Ttr", ]

# only logFC > 0.1
c0_DE_AD_ADp40KO_padj <- c0_DE_AD_ADp40KO[abs(c0_DE_AD_ADp40KO$avg_logFC) > 0.1, ]
# remove Ttr
c0_DE_AD_ADp40KO_padj <- c0_DE_AD_ADp40KO_padj[c0_DE_AD_ADp40KO_padj$X != "Ttr", ]

c0_DE_AD_ADp40KO_padj <- c0_DE_AD_ADp40KO_padj[which(c0_DE_AD_ADp40KO_padj$p_val_adj < 0.05), ]

datatable(c0_DE_AD_ADp40KO_padj, options = list(pageLength = 5, dom = 'tip'))

```

#### 3-2. DE cluster 10

```{r warning=FALSE, message=FALSE}
c10_DE_AD_ADp40KO <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/20200117_Clustering_DE_by_MAST_each_Cluster_10ADp40KO_AD_corrected.csv")

# reverse logFC2
c10_DE_AD_ADp40KO$avg_logFC <- c10_DE_AD_ADp40KO$avg_logFC * -1

c10_DE_AD_ADp40KO2 <- c10_DE_AD_ADp40KO[abs(c10_DE_AD_ADp40KO$avg_logFC) > 0.1, ]
# remove Ttr
c10_DE_AD_ADp40KO2 <- c10_DE_AD_ADp40KO2[c10_DE_AD_ADp40KO2$X != "Ttr", ]

# only logFC > 0.1
c10_DE_AD_ADp40KO_padj <- c10_DE_AD_ADp40KO[abs(c10_DE_AD_ADp40KO$avg_logFC) > 0.1, ]
# remove Ttr
c10_DE_AD_ADp40KO_padj <- c10_DE_AD_ADp40KO_padj[c10_DE_AD_ADp40KO_padj$X != "Ttr", ]

c10_DE_AD_ADp40KO_padj <- c10_DE_AD_ADp40KO_padj[which(c10_DE_AD_ADp40KO_padj$p_val_adj < 0.05), ]

datatable(c10_DE_AD_ADp40KO_padj, options = list(pageLength = 5, dom = 'tip'))

```