---
title: "Il genes"
author: "Skim"
date: '2020 3 31 '
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float: false
    code_folding: hide
---

Feature plot for below genes:

1) Il23r  
2) Il12rb1  
3) Il12rb2  
4) Il23a  
5) Il12a  

Be careful of scale. Every gene has different scale. 

```{r warning = FALSE, message = FALSE, fig.width= 10, fig.height= 7}
library(Seurat)
library(ggplot2)
library(dplyr)
library(gridExtra)
```

```{r warning = FALSE, message = FALSE}
load(file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200221_figure1_for_meeting_report_Seurat_object.Robj")

data9set_cleaned_Ctrl.SO <- subset(data9set_cleaned.SO, subset = sample %in% "Ctrl")
data9set_cleaned_AD.SO <- subset(data9set_cleaned.SO, subset = sample %in% "AD")
data9set_cleaned_ADp40KO.SO <- subset(data9set_cleaned.SO, subset = sample %in% "ADp40KO")
```

### 1. Il23r

```{r warning = FALSE, message = FALSE, fig.width= 15, fig.height= 5}
f1 <- FeaturePlot(data9set_cleaned_Ctrl.SO, features = "Il23r", order = TRUE, pt.size = 0.5)
f1 <- f1 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", midpoint = 1.5, limits=c(0, 2.5), breaks=c(0,1.5,2.5))  + ggtitle("Ctrl") + labs(y = "Il23r") + 
  theme(legend.position = "none",
        axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 15))


f2 <- FeaturePlot(data9set_cleaned_AD.SO, features = "Il23r", order = TRUE, pt.size = 0.5)
f2 <- f2 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", midpoint = 1.5, limits=c(0, 2.5), breaks=c(0,1.5,2.5)) + ggtitle("AD") + 
  theme(legend.position = "none",
        axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank())

f3 <- FeaturePlot(data9set_cleaned_ADp40KO.SO, features = "Il23r", order = TRUE, pt.size = 0.5)
f3 <- f3 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 2.5), midpoint = 1.5, breaks=c(0,1.5,2.5))  +   ggtitle("ADp40KO") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank())


grid.arrange(f1, f2, f3, ncol = 3, widths= c(1.1, 1.05, 1.2))
```

### 2. Il12rb1

```{r warning = FALSE, message = FALSE, fig.width= 15, fig.height= 5}
f1 <- FeaturePlot(data9set_cleaned_Ctrl.SO, features = "Il12rb1", order = TRUE, pt.size = 0.5)
f1 <- f1 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3), midpoint = 1.5, breaks=c(0,1.5,3))  + 
  ggtitle("Ctrl") + labs(y = "Il12rb1") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 15),
        legend.position = "none")


f2 <- FeaturePlot(data9set_cleaned_AD.SO, features = "Il12rb1", order = TRUE, pt.size = 0.5)
f2 <- f2 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3), midpoint = 1.5, breaks=c(0,1.5,3)) + 
  ggtitle("AD") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank(),
        legend.position = "none")

f3 <- FeaturePlot(data9set_cleaned_ADp40KO.SO, features = "Il12rb1", order = TRUE, pt.size = 0.5)
f3 <- f3 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3), midpoint = 1.5, breaks=c(0,1.5,3))  +   
  ggtitle("ADp40KO") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank())


grid.arrange(f1, f2, f3, ncol = 3, widths= c(1.1, 1.05, 1.2))
```

### 3. Il12rb2

```{r warning = FALSE, message = FALSE, fig.width= 15, fig.height= 5}
f1 <- FeaturePlot(data9set_cleaned_Ctrl.SO, features = "Il12rb2", order = TRUE, pt.size = 0.5)
f1 <- f1 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3.5), midpoint = 2, breaks=c(0,2,3.5))  + 
  ggtitle("Ctrl") + labs(y = "Il12rb2") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 15),
        legend.position = "none")


f2 <- FeaturePlot(data9set_cleaned_AD.SO, features = "Il12rb2", order = TRUE, pt.size = 0.5)
f2 <- f2 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3.5), midpoint = 2, breaks=c(0,2,4)) + 
  ggtitle("AD") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank(),
        legend.position = "none")

f3 <- FeaturePlot(data9set_cleaned_ADp40KO.SO, features = "Il12rb2", order = TRUE, pt.size = 0.5)
f3 <- f3 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3.5), midpoint = 2, breaks=c(0,2,3.5))  +   
  ggtitle("ADp40KO") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank())


grid.arrange(f1, f2, f3, ncol = 3, widths= c(1.1, 1.05, 1.2))
```

### 4. Il23a

```{r warning = FALSE, message = FALSE, fig.width= 15, fig.height= 5}
f1 <- FeaturePlot(data9set_cleaned_Ctrl.SO, features = "Il23a", order = TRUE, pt.size = 0.5)
f1 <- f1 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3), midpoint = 1.5, breaks=c(0,1.5,3))  + 
  ggtitle("Ctrl") + labs(y = "Il23a") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 15),
        legend.position = "none")


f2 <- FeaturePlot(data9set_cleaned_AD.SO, features = "Il23a", order = TRUE, pt.size = 0.5)
f2 <- f2 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3), midpoint = 1.5, breaks=c(0,1.5,3)) + 
  ggtitle("AD") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank(),
        legend.position = "none")

f3 <- FeaturePlot(data9set_cleaned_ADp40KO.SO, features = "Il23a", order = TRUE, pt.size = 0.5)
f3 <- f3 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3), midpoint = 1.5, breaks=c(0,1.5,3))  +   
  ggtitle("ADp40KO") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank())


grid.arrange(f1, f2, f3, ncol = 3, widths= c(1.1, 1.05, 1.2))
```

### 5. Il12a

```{r warning = FALSE, message = FALSE, fig.width= 15, fig.height= 5}
f1 <- FeaturePlot(data9set_cleaned_Ctrl.SO, features = "Il12a", order = TRUE, pt.size = 0.5)
f1 <- f1 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3.5), midpoint = 2, breaks=c(0,2,3.5))  + 
  ggtitle("Ctrl") + labs(y = "Il12a") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 15),
        legend.position = "none")


f2 <- FeaturePlot(data9set_cleaned_AD.SO, features = "Il12a", order = TRUE, pt.size = 0.5)
f2 <- f2 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3.5), midpoint = 2, breaks=c(0,2,3.5)) + 
  ggtitle("AD") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank(),
        legend.position = "none")

f3 <- FeaturePlot(data9set_cleaned_ADp40KO.SO, features = "Il12a", order = TRUE, pt.size = 0.5)
f3 <- f3 + scale_color_gradient2(low="#003366", high='#FFCC00', mid="#66FFFF", limits=c(0, 3.5), midpoint = 2, breaks=c(0,2,3.5))  +   
  ggtitle("ADp40KO") + 
  theme(axis.line=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank(),
        axis.title = element_blank())


grid.arrange(f1, f2, f3, ncol = 3, widths= c(1.1, 1.05, 1.2))
```


```{r}
sessionInfo()
```