---
title: "MG_3rd analysis"
author: "Skim"
date: "2/27/2020"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float: false
    code_folding: hide
---

```{r warning=FALSE, message=FALSE}
#Sys.setenv(PYTHONPATH="/data/local/rajewsky/shared_libs/python")
#library(reticulate)
#use_python("/usr/bin/python3", required = TRUE)
library(Seurat)
library(ggplot2)
library(dplyr)
library(DT)
library(gridExtra)
library(nichenetr)
library(tidyverse)
library(irr)
library(fgsea)
library(MAST)
library(ggrepel)
library(biomaRt)
library(topGO)
library(viridis)
library(destiny)
source("/data/rajewsky/home/skim/Microglia_Heppner/Codes/DroNc_AD/src/TopGO_scRNA.R")
#Rscript -e "library(rmarkdown); rmarkdown::render('/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20191229_pre_analysis_9sets.Rmd')"
```

```{r warning=FALSE, message=FALSE}
load(file="/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200210_figures_for_meeting_report_cleaned_Seurat_object_res0.8.Robj")
data9set_cleaned_MG.SO <- subset(data9set_cleaned.SO, subset = seurat_clusters %in% c(3, 8))
```

In here, I checked some genes identified in CellphoneDB analysis

#### 1. Ttr gene

Enriched in Ctrl and AD in Microglia

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=4}
f1 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Ttr"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "Ctrl", ])) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30)) + ggtitle("Ttr gene Ctrl") + theme(legend.position = "none")
f2 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Ttr"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "AD", ])) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Ttr gene AD") + theme(legend.position = "none")
f3 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Ttr"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "ADp40KO", ])) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Ttr gene ADp40KO")

grid.arrange(f1, f2, f3, ncol = 3, widths = c(1, 1, 1.15))

```

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=4}
FeaturePlot(data9set_cleaned.SO, features = "Ttr", split.by = "sample")
```

featureplot of paired Ddr1 gene

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=4}
FeaturePlot(data9set_cleaned.SO, features = "Ddr1", split.by = "sample")
```

#### 2. Ptn gene

Enriched in Ctrl and AD in Microglia

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=4}
f1 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Ptn"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "Ctrl", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30)) + ggtitle("Ptn gene Ctrl") + theme(legend.position = "none")
f2 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Ptn"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "AD", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Ptn gene AD") + theme(legend.position = "none")
f3 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Ptn"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "ADp40KO", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Ptn gene ADp40KO")

grid.arrange(f1, f2, f3, ncol = 3, widths = c(1, 1, 1.15))

```

#### 3. Csf1 gene

Enriched in AD only in Microglia

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=4}
f1 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Csf1"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "Ctrl", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30)) + ggtitle("Csf1 gene Ctrl") + theme(legend.position = "none")
f2 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Csf1"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "AD", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Csf1 gene AD") + theme(legend.position = "none")
f3 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Csf1"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "ADp40KO", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Csf1 gene ADp40KO")

grid.arrange(f1, f2, f3, ncol = 3, widths = c(1, 1, 1.15))

```

#### 4. Nrp2 gene

Enriched in AD and ADp40KO in Microglia

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=4}
f1 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Nrp2"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "Ctrl", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30)) + ggtitle("Nrp2 gene Ctrl") + theme(legend.position = "none")
f2 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Nrp2"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "AD", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Nrp2 gene AD") + theme(legend.position = "none")
f3 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Nrp2"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "ADp40KO", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Nrp2 gene ADp40KO")

grid.arrange(f1, f2, f3, ncol = 3, widths = c(1, 1, 1.15))

```

#### 5. Igf1 gene

Enriched in AD and ADp40KO in Microglia

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=4}
f1 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Igf1"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "Ctrl", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30)) + ggtitle("Igf1 gene Ctrl") + theme(legend.position = "none")
f2 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Igf1"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "AD", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Igf1 gene AD") + theme(legend.position = "none")
f3 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Igf1"), cells =  rownames(data9set_cleaned_MG.SO@meta.data[data9set_cleaned_MG.SO@meta.data$sample == "ADp40KO", ]), order = TRUE) + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))  + ggtitle("Igf1 gene ADp40KO")

grid.arrange(f1, f2, f3, ncol = 3, widths = c(1, 1, 1.15))

```

```{r}
# remove less expressed of 50% genes
RamDA_DGEm$portion <- rowSums(RamDA_DGEm != 0)/456
RamDA_DGEm <- subset(RamDA_DGEm, RamDA_DGEm$portion > 0.5)
RamDA_DGEm$portion <- NULL

###############################################################
# test
df <- data.frame(a = c(1,2,0), b = c(2,1,3), c = c(4,0,0))
df$portion <- rowSums(df != 0 )/3
subset(df, df$portion > 0.5)
# measure var
df$var <- apply(df, MARGIN = 1, FUN=var, na.rm = TRUE)

###############################################################
###########################################################################

RamDA_DGEm$var <- apply(RamDA_DGEm, MARGIN = 1, FUN=var, na.rm = TRUE)
summary(RamDA_DGEm$var)
RamDA_DGEm <- subset(RamDA_DGEm, RamDA_DGEm$var > 14) # more than 3rd QTR 
RamDA_DGEm$var <- NULL

RamDA_DGEm2 <- as.data.frame(t(RamDA_DGEm))
rownames(RamDA_DGEm2)

#### CAUTION ####
# expressionset has to be numeric, otherwise it will fail to create feaeture in expressionset
#################
# changing integer to numeric in all data frame
RamDA_DGEm2 <- as.data.frame(lapply(RamDA_DGEm2, as.numeric)) 

# Add cell id to matrix
RamDA_DGEm2$Cell <- colnames(RamDA_DGEm)
rownames(RamDA_DGEm2) <- NULL

# last cell column move to first column 
RamDA_DGEm2 <- RamDA_DGEm2[, c(12640, 1:12639)]

# if cell cycle
RamDA_DGEm2 <- RamDA_DGEm2[, c(456, 1:455)]

#RamDA_DGEm2$Cell <- rownames(RamDA_DGEm2)
#RamDA_DGEm2$Cell <- as.factor(RamDA_DGEm2$Cell)

ct <- as.ExpressionSet(RamDA_DGEm2)
dm <- DiffusionMap(ct)
plot(dm, c(2,3))

foo <- data.frame(DC2 = dm$DC2, DC3 = dm$DC3)
foo$ID <- colnames(RamDA_DGEm)
foo$time <- c(rep("0h", 92), rep("12h", 91), rep("24h", 93), rep("48h", 87), rep("96h", 93)) 

ggplot(foo, aes(x = DC2, y = DC3, color = time)) + geom_point()
```

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=4}

ct <- as.SingleCellExperiment(data9set_cleaned_MG.SO)
dm <- DiffusionMap(ct)

ct <- as.ExpressionSet(RamDA_DGEm2)
dm <- DiffusionMap(ct)
plot(dm, c(2,3))

foo <- data.frame(DC2 = dm$DC2, DC3 = dm$DC3)
foo$ID <- colnames(RamDA_DGEm)
foo$time <- c(rep("0h", 92), rep("12h", 91), rep("24h", 93), rep("48h", 87), rep("96h", 93))

ggplot(foo, aes(x = DC2, y = DC3, color = time)) + geom_point()



```







