---
title: "MG 2nd analysis"
author: "Skim"
date: '2020 2 15 '
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float: false
    code_folding: hide
---

```{r warning=FALSE, message=FALSE}
#Sys.setenv(PYTHONPATH="/data/local/rajewsky/shared_libs/python")
#library(reticulate)
#use_python("/usr/bin/python3", required = TRUE)
library(Seurat)
library(ggplot2)
library(dplyr)
library(DT)
library(gridExtra)
library(nichenetr)
library(tidyverse)
library(irr)
library(fgsea)
library(MAST)
library(ggrepel)
library(biomaRt)
library(topGO)
library(viridis)
source("/data/rajewsky/home/skim/Microglia_Heppner/Codes/DroNc_AD/src/TopGO_scRNA.R")
#Rscript -e "library(rmarkdown); rmarkdown::render('/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20191229_pre_analysis_9sets.Rmd')"
```

```{r warning=FALSE, message=FALSE}
load(file="/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200210_figures_for_meeting_report_cleaned_Seurat_object_res0.8.Robj")

```

## 1. MG cluster analysis

This analysis is done by subset 3 Microglia clusters (from res 0.8 and cluster 34 was removed) and I investigate more in here.

```{r warning=FALSE, message=FALSE, fig.width = 6, fig.height=5}
data9set_cleaned_MG.SO <- subset(data9set_cleaned.SO, subset = seurat_clusters %in% c(3, 8, 37))

d1 <- DimPlot(object = data9set_cleaned_MG.SO, reduction = "umap", group.by = "seurat_clusters") + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30)) 
d1
```

```{r warning=FALSE, message=FALSE, fig.width= 12, fig.height=5}

#data9set.SO_MG@meta.data$sample <- ifelse((data9set.SO_MG$gemgroup == 1 | data9set.SO_MG$gemgroup == 4 | data9set.SO_MG$gemgroup == 7), "Ctrl", ifelse((data9set.SO_MG$gemgroup == 2 | data9set.SO_MG$gemgroup == 5 | data9set.SO_MG$gemgroup == 8), "AD", "ADp40KO"))

data9set_cleaned_MG.SO@meta.data$sample <- factor(data9set_cleaned_MG.SO@meta.data$sample, levels = c("Ctrl", "AD", "ADp40KO"))
d2 <- DimPlot(object = data9set_cleaned_MG.SO, group.by = "sample", pt.size = 0.05, split.by = "sample") 
d2 <- d2 + scale_colour_viridis_d() + scale_x_continuous(limits = c(-10,10)) + scale_y_continuous(limits = c(10, 30))
#grid.arrange(d1, d2, ncol = 2, widths = c(1, 1.15))
d2
```

### 2. exp type composition in each cluster

```{r warning=FALSE, message=FALSE, fig.height= 5, fig.width=5}
# ref: http://oshlacklab.com/combes-organoid-paper/07_Combined_Clustering.html#conserved_markers

plot.data <- data9set_cleaned_MG.SO@meta.data %>%
    dplyr::select(sample, cluster = seurat_clusters) %>%
    mutate(cluster = cluster) %>%
    group_by(cluster, sample) %>%
    summarise(count = n()) %>%
    mutate(clust_total = sum(count)) %>%
    mutate(clust_prop = count / clust_total) %>%
    group_by(sample) %>%
    mutate(dataset_total = sum(count)) %>%
    ungroup() %>%
    mutate(dataset_prop = count / dataset_total)

plot.data$sample <- factor(plot.data$sample, levels = c("Ctrl", "AD", "ADp40KO"))

ggplot(plot.data, aes(x = cluster, y = count, fill = sample)) +
    geom_col() + 
  theme_classic() + 
  scale_y_continuous(limits = c(0, 4000), expand = c(0,0)) + 
  scale_fill_viridis_d() + 
  geom_text(aes(label = count), color = "darkgray", size = 3,  position = position_stack(0.5))
```

```{r warning=FALSE, message=FALSE, fig.height= 5, fig.width=5}
ggplot(plot.data, aes(x = cluster, y = clust_prop, fill = sample)) +
    geom_col() + theme_classic() + scale_y_continuous(expand = c(0,0)) + scale_fill_viridis_d() + 
  ylab("percentage") + 
  geom_text(aes(label = round(clust_prop, 3)), color = "darkgray", size = 4,  position = position_stack(0.5))

```

### 3. DE analysis (cluster 8 vs 3)

In here, I compare DE of cluster 8 vs 3

red dots are padj < 0.01

```{r warning=FALSE, message=FALSE, fig.width= 7, fig.height=5}
#data9set.SO_MG.marker8vs3 <- FindMarkers(data9set_cleaned_MG.SO, ident.1 =  "8", ident.2 = "3", group.by = "seurat_clusters", test.use = "MAST", logfc.threshold = 0, min.pct = 0.01)
#write.csv(data9set.SO_MG.marker8vs3, "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200215_MG_2nd_analysis_Cluster8_vs_3_marker.csv")

data9set.SO_MG.marker8vs3 <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200215_MG_2nd_analysis_Cluster8_vs_3_marker.csv", row.names = 1)
data9set.SO_MG.marker8vs3_padj <- data9set.SO_MG.marker8vs3[which(data9set.SO_MG.marker8vs3$p_val_adj < 0.01), ]

ggplot(data9set.SO_MG.marker8vs3) + geom_point(aes(x = avg_logFC, y = -log10(p_val_adj))) + 
  geom_point(data = data9set.SO_MG.marker8vs3_padj, aes(x = avg_logFC, y = -log10(p_val_adj)), color = "red") +
  ggtitle("DE analysis cluster 8 vs 3") + 
   xlab("log2 fold change") + 
  ylab("-log10(adjusted p-value)") +
  theme(legend.position = "none",
        plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = rel(1.25))) +
  geom_text_repel(aes(x = avg_logFC, y = -log10(p_val_adj), label = ifelse(-log10(data9set.SO_MG.marker8vs3$p_val_adj) > 200 , rownames(data9set.SO_MG.marker8vs3),""))) + theme_classic()
```

### 4. GO analysis (cluster 8 vs 3)

In here, I analyzed GO analysis

```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height=5}
GO_up.df <- scRNA_topGO(data9set.SO_MG.marker8vs3, InterestGenes = "up", logFC = 0.2)
GO_down.df <- scRNA_topGO(data9set.SO_MG.marker8vs3, InterestGenes = "down", logFC = 0.2)

GO_figure <- function(GO.df){
  GO.df <- GO.df[c(31:60), ]
  GO.df <- GO.df[GO.df$Annotated < 500 , ]
  GO.df <- GO.df[c(1:10), ]
  GO.df$Term <- factor(GO.df$Term, levels = GO.df$Term[order(GO.df$Fisher.elim, decreasing = TRUE)])

  ggplot(GO.df, aes(x=gene_ratio, 
               y=Term, 
               colour=Fisher.elim, 
               size=Significant)) +
        geom_point() +
        expand_limits(x=0) +
        labs(x="gene ratio", y="GO term", colour="p value", size="Significant")
}
g1 <- GO_figure(GO_up.df)
g2 <- GO_figure(GO_down.df)

grid.arrange(g1, g2, ncol = 2)
```

```{r warning=FALSE, message=FALSE, fig.width= 10, fig.height=5}
data9set_cleaned_MG.umap <- as.data.frame(data9set_cleaned_MG.SO@reductions$umap@cell.embeddings)
data9set_cleaned_MG.meta <- as.data.frame(data9set_cleaned_MG.SO@meta.data)

data9set_cleaned_MG.umap2 <- cbind(data9set_cleaned_MG.umap, data9set_cleaned_MG.meta)
data9set_cleaned_MG.umap_3 <- data9set_cleaned_MG.umap2[data9set_cleaned_MG.umap2$seurat_clusters == "3", ]

f1 <- ggplot(data9set_cleaned_MG.umap, aes(x = UMAP_1, y = UMAP_2)) + geom_point(color = "gray") + 
  geom_point(data = data9set_cleaned_MG.umap_3, aes(x = UMAP_1, y = UMAP_2), color = "#33CCFF") + 
  scale_x_continuous(limits = c(-7,7)) + scale_y_continuous(limits = c(18, 28)) + theme_void()

f2 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Clec7a"), pt.size = 1, order = TRUE) + xlim(limits = c(-7,7)) + ylim(limits = c(18, 28))
grid.arrange(f1, f2, ncol = 2)
```


```{r warning=FALSE, message=FALSE, fig.width= 15, fig.height=10}
f1 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Cx3cr1"), pt.size = 1, order = TRUE) + xlim(limits = c(-7,7)) + ylim(limits = c(18, 28))
f2 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Apoe"), pt.size = 1, order = TRUE) + xlim(limits = c(-7,7)) + ylim(limits = c(18, 28))
f3 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Cd9"), pt.size = 1, order = TRUE)+ xlim(limits = c(-7,7)) + ylim(limits = c(18, 28))
f4 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Hexb"), pt.size = 1, order = TRUE) + xlim(limits = c(-7,7)) + ylim(limits = c(18, 28))
f5 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Cst7"), pt.size = 1, order = TRUE)+ xlim(limits = c(-7,7)) + ylim(limits = c(18, 28))
f6 <- FeaturePlot(data9set_cleaned_MG.SO, features = c("Trem2"), pt.size = 1, order = TRUE) + xlim(limits = c(-7,7)) + ylim(limits = c(18, 28))



grid.arrange(f1, f2, f3, f4, f5, f6, ncol = 3)
```