---
title: "slingshot"
author: "Skim"
date: '2020 10 12 '
output: html_document
---

```{r warning=FALSE, message=FALSE, fig.height=8, fig.width=10}
library(tradeSeq)
library(RColorBrewer)
library(SingleCellExperiment)
library(slingshot)
library(monocle)
library(mclust, quietly = TRUE)
library(Seurat)
library(gridExtra)
library(dplyr)
require(mgcv, quietly = TRUE)
```

```{r warning=FALSE, message=FALSE, fig.height=8, fig.width=10}
# For reproducibility
RNGversion("3.5.0")
palette(brewer.pal(8, "Dark2"))
data(countMatrix, package = "tradeSeq")
counts <- as.matrix(countMatrix)
rm(countMatrix)
data(crv, package = "tradeSeq")
data(celltype, package = "tradeSeq")


load(file="/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200210_figures_for_meeting_report_cleaned_Seurat_object_res0.8.Robj")

data9set_cleaned.SO$cell_type <- data9set_cleaned.SO@active.ident

data9set_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Oligo", "OPC"))

data9set_sub.meta <- data9set_sub.SO@meta.data %>% as.data.frame

data9set_sub.meta$cell_barcode <- rownames(data9set_sub.meta)

data9set_sub.meta <- data9set_sub.meta %>% mutate(cell_type_precise = case_when(seurat_clusters %in% 6 ~ "MOL",
                                                                                            seurat_clusters %in% c(1,5) ~ "MFOL",
                                                                                            seurat_clusters %in% 12 ~ "OPC",
                                                                                            seurat_clusters %in% 38 ~ "NFOL"))

data9set_sub.meta <- data9set_sub.meta %>% mutate(color = case_when(seurat_clusters %in% 6 ~ "red",
                                                                                            seurat_clusters %in% c(1,5) ~ "orange",
                                                                                            seurat_clusters %in% 12 ~ "green",
                                                                                            seurat_clusters %in% 38 ~ "blue"))

rownames(data9set_sub.meta) <- data9set_sub.meta$cell_barcode



counts = GetAssayData(object = data9set_sub.SO, slot = "counts")

meta_sub.df <- data9set_sub.SO@meta.data

```



```{r warning=FALSE, message=FALSE, fig.height=8, fig.width=10}

sim <- SingleCellExperiment(assays = list(counts = GetAssayData(object = data9set_sub.SO, slot = "counts")))

geneFilter <- apply(assays(sim)$counts,1,function(x){
    sum(x >= 3) >= 10
})
sim <- sim[geneFilter, ]

counts <- counts[geneFilter, ] 
counts <- counts %>% as.matrix() %>% t()

FQnorm <- function(counts){
    rk <- apply(counts,2,rank,ties.method='min')
    counts.sort <- apply(counts,2,sort)
    refdist <- apply(counts.sort,1,median)
    norm <- apply(rk,2,function(r){ refdist[r] })
    rownames(norm) <- rownames(counts)
    return(norm)
}

assays(sim)$norm <- FQnorm(assays(sim)$counts)

pca <- prcomp(t(log1p(assays(sim)$norm)), scale. = FALSE)

```

```{r warning=FALSE, message=FALSE, fig.height=8, fig.width=10}
rd <- pca$x[,1:3]

reducedDims(sim) <- SimpleList(PCA = rd)
cl <- Mclust(rd, G = 4)$classification
colData(sim)$GMM <- cl

simu_slingshot <- slingshot(sim, clusterLabels = 'GMM', reducedDim = 'PCA')

colors <- colorRampPalette(brewer.pal(11,'Spectral')[-6])(100)
plotcol <- colors[cut(sim$GMM, breaks=100)]

plotcol.df <- plotcol %>% as.data.frame
simu.meta <- simu_slingshot@int_colData@listData$reducedDims@listData$PCA %>% as.data.frame
modifiend_color <- data9set_sub.meta$color %>% as.vector


plot(reducedDims(simu_slingshot)$PCA, pch=16, asp = 1, col = modifiend_color)
savelines <- lines(SlingshotDataSet(simu_slingshot), lwd=2, col='black')

save(simu_slingshot, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20201012_slingshot_Test/simu_slingshot")


exp <- SlingshotDataSet(simu_slingshot)

test_curve <- exp@curves$curve1$lambda %>% as.data.frame
saveRDS(test_curve, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20201012_slingshot_Test/curve1_lambda.txt")

test_curve2 <- exp@curves$curve1$ord %>% as.data.frame
saveRDS(test_curve2, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20201012_slingshot_Test/curve1_ord.txt")



t1 <- simu_slingshot$slingPseudotime_1
t1.df <- t1 %>% as.data.frame
saveRDS(t1.df, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20201012_slingshot_Test/slingPseudotime_1.txt")


t <- simu_slingshot$slingPseudotime_2
t.df <- t %>% as.data.frame
saveRDS(t.df, file = "/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20201012_slingshot_Test/slingPseudotime_2.txt")



lin <- getLineages(sim, clusterLabels = colData(simu_slingshot)$GMM)

crv <- getCurves(lin) %>% SlingshotDataSet()


test.df <- crv@curves$curve1$ord %>% as.data.frame


```

