---
title: "edgeR_plots"
author: "Skim"
date: '2020 8 29 '
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float: false
    code_folding: hide
---

This figures is for volcano plots / scatter plots of each cell type by edgeR

```{r warning=FALSE, message=FALSE}
library(gridExtra)
library(dplyr)
library(ggplot2)
library(tidyr)
library(Seurat)
library(ggrepel)

load(file="/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200210_figures_for_meeting_report_cleaned_Seurat_object_res0.8.Robj")
```

```{r warning=FALSE, message=FALSE}
meta.df <- data9set_cleaned.SO@meta.data %>% mutate(cell_type = case_when(seurat_clusters %in% c(0, 10) ~ "Dentate_Gyrus",
                                                                                             seurat_clusters %in% c(2, 13, 18, 40) ~ "CA1",
                                                                                             seurat_clusters %in% c(9, 21, 27, 32) ~ "CA2_3",
                                                                                             seurat_clusters %in% c(11, 14, 15, 17, 19, 20) ~ "subiculum",
                                                                                             seurat_clusters %in% c(24, 29) ~ "Unidentified_Neurons",
                                                                                             seurat_clusters %in% c(7, 16, 22, 30) ~ "Inhibitory_Neurons",
                                                                                             seurat_clusters %in% c(6) ~ "MOL",
                                                                                             seurat_clusters %in% c(1, 5) ~ "MFOL",
                                                                                             seurat_clusters %in% c(12) ~ "NFOL",
                                                                                             seurat_clusters %in% c(38) ~ "OPC",
                                                                                             seurat_clusters %in% c(3, 8) ~ "Microglia",
                                                                                             seurat_clusters %in% c(4) ~ "Astrocytes",
                                                                                             seurat_clusters %in% c(36) ~ "Vascular",
                                                                                             seurat_clusters %in% c(39) ~ "VLMC",
                                                                                             seurat_clusters %in% c(26) ~ "Choroid",
                                                                                             seurat_clusters %in% c(23) ~ "Fibroblast",
                                                                                             seurat_clusters %in% c(28) ~ "Cajal",
                                                                                             seurat_clusters %in% c(35) ~ "Pericyte",
                                                                                             seurat_clusters %in% c(37) ~ "Macrophage"))


data9set_cleaned.SO$cell_type <- meta.df$cell_type

# give levels to large cell type
data9set_cleaned.SO$cell_type <- factor(data9set_cleaned.SO$cell_type, levels = c("Dentate_Gyrus", "CA1", "CA2_3", "subiculum",  "Unidentified_Neurons", 
                                                                                  "Inhibitory_Neurons", "MOL", "MFOL", "OPC", "NFOL", "Microglia","Astrocytes",
                                                                                  "Vascular", "VLMC", "Choroid", "Fibroblast", "Cajal", "Pericyte", "Macrophage"))

```

```{r warning=FALSE, message=FALSE}

CPM_calculation <- function(data9set_29.SO){
  data9set_29_ctrl.SO <- subset(data9set_29.SO, subset = sample %in% "Ctrl")
data9set_29_AD.SO <- subset(data9set_29.SO, subset = sample %in% "AD")
data9set_29_ADp40KO.SO <- subset(data9set_29.SO, subset = sample %in% "ADp40KO")


# 1. for ctrl
data9set_cleaned_29_ctrl.df <- as.data.frame(data9set_29_ctrl.SO@assays$RNA@counts)
cpm <- apply(data9set_cleaned_29_ctrl.df, 2, function(x) (x/sum(x))*1000000)
cpm.df <- rowMeans(cpm) %>% as.data.frame

# add pseudocount 1
cpm.df <- cpm.df + 1

# log2
cpm_log2.df <- as.data.frame(lapply(cpm.df, log2), row.names = rownames(cpm.df))

# 2. for AD
data9set_cleaned_29_AD.df <- as.data.frame(data9set_29_AD.SO@assays$RNA@counts)
cpm2 <- apply(data9set_cleaned_29_AD.df, 2, function(x) (x/sum(x))*1000000)
cpm2.df <- rowMeans(cpm2) %>% as.data.frame

# add pseudocount 1
cpm2.df <- cpm2.df + 1

# log2
cpm2_log2.df <- as.data.frame(lapply(cpm2.df, log2), row.names = rownames(cpm2.df))

# 3. for ADp40KO
data9set_cleaned_29_ADp40KO.df <- as.data.frame(data9set_29_ADp40KO.SO@assays$RNA@counts)
cpm3 <- apply(data9set_cleaned_29_ADp40KO.df, 2, function(x) (x/sum(x))*1000000)
cpm3.df <- rowMeans(cpm3) %>% as.data.frame

# add pseudocount 1
cpm3.df <- cpm3.df + 1

# log2
cpm3_log2.df <- as.data.frame(lapply(cpm3.df, log2), row.names = rownames(cpm3.df))

cpm_final <- cbind(cpm_log2.df, cpm2_log2.df, cpm3_log2.df)

colnames(cpm_final) <- c("WT", "AD", "ADp40KO")

return(cpm_final)
}

scatter_plot <- function(cpm_final, x_axis = WT, y_axis = AD, xlabel = "x label", ylabel = "y label", cpm_final_sub){
  ggplot(cpm_final, aes_string(x = x_axis, y = y_axis)) + geom_point(size = 1, color = "#666666", alpha = 0.2 ) +
  geom_point(data = cpm_final_sub, aes_string(x = x_axis, y = y_axis), color = "red") + 
  theme_classic() + scale_x_continuous(expand = c(0,0), limits = c(0, 15)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,15)) + 
  xlab(xlabel) +
  ylab(ylabel) +
  theme(plot.title = element_text(size = 16, hjust = 0.5, family = "helvetica"),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 12, color = "black")) +
  geom_abline(slope = 1, color="red", linetype="dashed", size=.5) +
  geom_text_repel(data = cpm_final_sub, aes_string(x = x_axis, y = y_axis), label = rownames(cpm_final_sub))
}

```

```{r warning=FALSE, message=FALSE}
volcano_plot <- function(DE.df, DE.df_plus, DE.df_minus, DE.df_il12, title = "title", y_lim = c(0,20), x_lim = c(-1, 1), plus_threshold = 1E-5, minus_threshold = 1E-5, plus_force = 10, minus_force = 10){
  ggplot(DE.df) + geom_point(aes(x = logFC, y = -log10(FDR))) +
  geom_point(data = DE.df_plus, aes(x = logFC, y = -log10(FDR)), color = "red") +
  geom_point(data = DE.df_minus, aes(x = logFC, y = -log10(FDR)), color = "blue") +
  ggtitle(title) + 
  theme_classic() + 
  xlab("log fold change") + 
  ylab("-log10(adjusted p-value)") +
  scale_y_continuous(expand = c(0,0), limits = y_lim) + xlim(x_lim) + 
  theme(legend.position = "none",
        plot.title = element_text(size = 15, hjust = 0.5, family = "helvetica"),
        axis.title = element_text(size = 15), 
        axis.text = element_text(size = 12, color = "black")) +
  geom_text_repel(data = DE.df_plus[DE.df_plus$FDR < plus_threshold, ], aes(x = logFC, y = -log10(FDR)), label = DE.df_plus[DE.df_plus$FDR < plus_threshold, ]$gene, force = plus_force) + 
  geom_text_repel(data = DE.df_minus[DE.df_minus$FDR < minus_threshold, ], aes(x = logFC, y = -log10(FDR)), label = DE.df_minus[DE.df_minus$FDR < minus_threshold, ]$gene, force = minus_force) + 
  geom_text_repel(data = DE.df_il12, aes(x = logFC, y = -log10(FDR)), label = DE.df_il12$gene)
  
}

```

### 1. MOL

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/MOL_AD_Ctrl.csv", row.names = 1)

AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "MOL APPPS1 vs WT", minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/MOL_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]


AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "MOL APPPS1 vs APPPS1.il12b-/-", minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/MOL_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "MOL APPPS1.il12b-/- vs WT", y_lim = c(0,25), plus_threshold = 1E-7, minus_threshold = 1E-7, minus_force = 20)

grid.arrange(v1, v2, v3, ncol = 3)
```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "MOL APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,25), minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "MOL APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1), y_lim = c(0,25),  minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "MOL APPPS1.il12b-/- vs WT", x_lim = c(-1, 1), y_lim = c(0,25), plus_threshold = 1E-7, minus_threshold = 1E-7, minus_force = 20)

grid.arrange(v1, v2, v3, ncol = 3)
```


```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("MOL"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("C4b", "Tenm2", "Il12b", "Snhg11", "Meg3", "Pttg1", "Rnf220", "Eml1"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Tenm2", "Il12b","Pttg1", "Slc8a1", "Elmo1", "Zfand4", "Shtn1", "Rnf220", "St18"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("C4b", "Il12b", "Snhg11","Pttg1", "Piezo2", "Thy1", "Dcc", "Gm37459", "Eml1", "Pex5I"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 MOL WT samples", ylabel = "log2 average CPM + 1 MOL APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 MOL APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 MOL APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 MOL WT samples", ylabel = "log2 average CPM + 1 MOL APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```


### 2. MFOL

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/MFOL_AD_Ctrl.csv", row.names = 1)

AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "MFOL APPPS1 vs WT", y_lim = c(0,80), plus_threshold = 1E-25, minus_threshold = 1E-20, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/MFOL_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]


AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "MFOL APPPS1 vs APPPS1.il12b-/-",  y_lim = c(0,80), plus_threshold = 1E-25, minus_threshold = 1E-20, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/MFOL_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "MFOL APPPS1.il12b-/- vs WT", y_lim = c(0,100), plus_threshold = 1E-30, minus_threshold = 1E-35, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)


```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "MFOL APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,100), plus_threshold = 1E-25, minus_threshold = 1E-20, plus_force = 5, minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "MFOL APPPS1 vs APPPS1.il12b-/-",  x_lim = c(-1, 1), y_lim = c(0,100), plus_threshold = 1E-25, minus_threshold = 1E-20, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "MFOL APPPS1.il12b-/- vs WT", x_lim = c(-1, 1), y_lim = c(0,100), plus_threshold = 1E-30, minus_threshold = 1E-35, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)
```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("MFOL"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("C4b", "Tenm2", "Il12b", "Thy1", "Zbtb16", "Pttg1", "Rnf220", "Eml1"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Tenm2", "Il12b","Pttg1", "Otud7a", "Plcl1", "Spock1", "Mast4", "Rnf220", "Elmo1"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("C4b", "Il12b", "Thy1","Pttg1", "Kirrel3", "Gm37459", "Plp1", "Pex5l", "Eml1", "Pex5I"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 MFOL WT samples", ylabel = "log2 average CPM + 1 MFOL APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 MFOL APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 MFOL APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 MFOL WT samples", ylabel = "log2 average CPM + 1 MFOL APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```


### 3. OPC

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/OPC_AD_Ctrl.csv", row.names = 1)

AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "OPC APPPS1 vs WT", x_lim = c(-2, 2), y_lim = c(0,5), plus_threshold = 1E-2, minus_threshold = 1E-2, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/OPC_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]


AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "OPC APPPS1 vs APPPS1.il12b-/-", x_lim = c(-2, 2), y_lim = c(0,10), plus_threshold = 1E-5, minus_threshold = 1E-5, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/OPC_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "OPC APPPS1.il12b-/- vs WT", x_lim = c(-2, 2), y_lim = c(0,2), plus_threshold = 1E-2, minus_threshold = 1E-2, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "OPC APPPS1 vs WT", x_lim = c(-2, 2), y_lim = c(0,10), plus_threshold = 1E-2, minus_threshold = 1E-2, plus_force = 5, minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "OPC APPPS1 vs APPPS1.il12b-/-", x_lim = c(-2, 2), y_lim = c(0,10), plus_threshold = 1E-5, minus_threshold = 1E-5, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "OPC APPPS1.il12b-/- vs WT", x_lim = c(-2, 2), y_lim = c(0,10), plus_threshold = 1E-2, minus_threshold = 1E-2, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)
```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("OPC"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("Ar", "A530053G22Rik", "Il12b", "Pttg1"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Grin2a", "Il12b","Pttg1"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("Il12b","Pttg1"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 OPC WT samples", ylabel = "log2 average CPM + 1 OPC APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 OPC APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 OPC APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 OPC WT samples", ylabel = "log2 average CPM + 1 OPC APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```

### 4. Astrocytes

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Astrocytes_AD_Ctrl.csv", row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Astrocytes APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,40), plus_threshold = 1E-15, minus_threshold = 1E-15, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Astrocytes_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Astrocytes APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1), y_lim = c(0,40), plus_threshold = 1E-10, minus_threshold = 1E-10, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Astrocytes_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Astrocytes APPPS1.il12b-/- vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,50), plus_threshold = 1E-25, minus_threshold = 1E-25, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Astrocytes APPPS1 vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,50), plus_threshold = 1E-15, minus_threshold = 1E-15, plus_force = 5, minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Astrocytes APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1.5, 1.5), y_lim = c(0,50), plus_threshold = 1E-10, minus_threshold = 1E-10, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Astrocytes APPPS1.il12b-/- vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,50), plus_threshold = 1E-25, minus_threshold = 1E-25, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```


```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Astrocytes"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("Plce1", "Gfap", "Il12b", "Pttg1", "Mt1", "Enox1", "Grm3"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Asic2", "Il12b","Pttg1", "Mdga2", "Galnt18", "Kcnd3", "Zswim6"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("Il12b","Pttg1", "Gfap", "Usp53", "Pde10a", "Rora"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 Astrocytes WT samples", ylabel = "log2 average CPM + 1 Astrocytes APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 Astrocytes APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 Astrocytes APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 Astrocytes WT samples", ylabel = "log2 average CPM + 1 Astrocytes APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```

### 5. Microglia

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Microglia_AD_Ctrl.csv", row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Microglia APPPS1 vs WT", x_lim = c(-1, 2.5), y_lim = c(0,150), plus_threshold = 1E-50, minus_threshold = 1E-35, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Microglia_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Microglia APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1), y_lim = c(0,45), plus_threshold = 1E-10, minus_threshold = 1E-10, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Microglia_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Microglia APPPS1.il12b-/- vs WT", x_lim = c(-1, 2), y_lim = c(0,120), plus_threshold = 1E-60, minus_threshold = 1E-40, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Microglia APPPS1 vs WT", x_lim = c(-2.5, 2.5), y_lim = c(0,150), plus_threshold = 1E-50, minus_threshold = 1E-35, plus_force = 5, minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Microglia APPPS1 vs APPPS1.il12b-/-", x_lim = c(-2.5, 2.5), y_lim = c(0,150), plus_threshold = 1E-10, minus_threshold = 1E-10, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Microglia APPPS1.il12b-/- vs WT", x_lim = c(-2.5, 2.5), y_lim = c(0,150), plus_threshold = 1E-60, minus_threshold = 1E-40, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)
```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Microglia"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("Ank", "Ctnna3", "Il12b", "Pttg1", "Etl4", "Myo1e", "Fgf13", "Cacna1a","Zfhx3"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Ctnna3", "Il12b","Pttg1", "Anxa3", "Fkbp5"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("Il12b","Pttg1", "Fgf13", "Etl4", "Myo1e", "Ank", "Apbb2", "Zfhx3", "Elmo1"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 Microglia WT samples", ylabel = "log2 average CPM + 1 Microglia APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 Microglia APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 Microglia APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 Microglia WT samples", ylabel = "log2 average CPM + 1 Microglia APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```


### 6. Dentate Gyrus

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Dentate_Gyrus_AD_Ctrl.csv", row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Dentate Gyrus APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,120), plus_threshold = 1E-30, minus_threshold = 1E-30, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Dentate_Gyrus_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Dentate Gyrus APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1), y_lim = c(0,100), plus_threshold = 1E-40, minus_threshold = 1E-40, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Dentate_Gyrus_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Dentate Gyrus APPPS1.il12b-/- vs WT", x_lim = c(-1, 1), y_lim = c(0,170), plus_threshold = 1E-60, minus_threshold = 1E-40, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Dentate Gyrus APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,170), plus_threshold = 1E-30, minus_threshold = 1E-30, plus_force = 5, minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Dentate Gyrus APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1), y_lim = c(0,170), plus_threshold = 1E-40, minus_threshold = 1E-40, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Dentate Gyrus APPPS1.il12b-/- vs WT", x_lim = c(-1, 1), y_lim = c(0,170), plus_threshold = 1E-60, minus_threshold = 1E-40, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```


```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Dentate_Gyrus"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("Thy1", "Rsrp1", "Il12b", "Pttg1", "Zfp804b", "Nrxn3"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Pdzd2", "Il12b","Pttg1", "Maml2", "Fth1"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("Il12b","Pttg1", "Thy1", "Tenm4"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 Dentate Gyrus WT samples", ylabel = "log2 average CPM + 1 Dentate Gyrus APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 Dentate Gyrus APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 Dentate Gyrus APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 Dentate Gyrus WT samples", ylabel = "log2 average CPM + 1 Dentate Gyrus APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```

### 7. CA1

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/CA1_AD_Ctrl.csv", row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "CA1 APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,120), plus_threshold = 1E-30, minus_threshold = 1E-30, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/CA1_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "CA1 APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1), y_lim = c(0,110), plus_threshold = 1E-40, minus_threshold = 1E-40, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/CA1_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "CA1 APPPS1.il12b-/- vs WT", x_lim = c(-1, 1.5), y_lim = c(0,160), plus_threshold = 1E-60, minus_threshold = 1E-40, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "CA1 APPPS1 vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,160), plus_threshold = 1E-30, minus_threshold = 1E-30, plus_force = 5, minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "CA1 APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1.5, 1.5), y_lim = c(0,160), plus_threshold = 1E-40, minus_threshold = 1E-40, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "CA1 APPPS1.il12b-/- vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,160), plus_threshold = 1E-60, minus_threshold = 1E-40, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("CA1"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("Thy1", "Rsrp1", "Il12b", "Pttg1", "Fgf1", "Arhgap26"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Gm12132", "Il12b","Pttg1", "Homer1"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("Il12b","Pttg1", "Thy1", "Lrrc4c"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 CA1 WT samples", ylabel = "log2 average CPM + 1 CA1 APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 CA1 APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 CA1 APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 CA1 WT samples", ylabel = "log2 average CPM + 1 CA1 APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```

### 8. CA2/3

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/CA2_3_AD_Ctrl.csv", row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "CA2/3 APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,40), plus_threshold = 1E-15, minus_threshold = 1E-10, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/CA2_3_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "CA2/3 APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1), y_lim = c(0,45), plus_threshold = 1E-20, minus_threshold = 1E-15, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/CA2_3_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "CA2/3 APPPS1.il12b-/- vs WT", x_lim = c(-1, 1.5), y_lim = c(0,60), plus_threshold = 1E-20, minus_threshold = 1E-20, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

``` 

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "CA2/3 APPPS1 vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,60), plus_threshold = 1E-15, minus_threshold = 1E-10, plus_force = 5, minus_force = 20)

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "CA2/3 APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1.5, 1.5), y_lim = c(0,60), plus_threshold = 1E-20, minus_threshold = 1E-15, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "CA2/3 APPPS1.il12b-/- vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,60), plus_threshold = 1E-20, minus_threshold = 1E-20, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

``` 


```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("CA2_3"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("Thy1", "Rsrp1", "Il12b", "Pttg1", "Rnf112", "Arhgef25"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Gm12296", "Il12b","Pttg1", "Dcc"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("Il12b","Pttg1", "Thy1", "Gm12296", "Ube3a", "Lrrc4c"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 CA2/3 WT samples", ylabel = "log2 average CPM + 1 CA2/3 APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 CA2/3 APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 CA2/3 APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 CA2/3 WT samples", ylabel = "log2 average CPM + 1 CA2/3 APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```

### 9. Subiculum

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/subiculum_AD_Ctrl.csv", row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "subiculum APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,70), plus_threshold = 1E-35, minus_threshold = 1E-25, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/subiculum_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "subiculum APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1.5), y_lim = c(0,90), plus_threshold = 1E-30, minus_threshold = 1E-30, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/subiculum_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "subiculum APPPS1.il12b-/- vs WT", x_lim = c(-1, 1.5), y_lim = c(0,160), plus_threshold = 1E-30, minus_threshold = 1E-20, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```  


```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "subiculum APPPS1 vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,160), plus_threshold = 1E-35, minus_threshold = 1E-25, plus_force = 5, minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "subiculum APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1.5, 1.5), y_lim = c(0,160), plus_threshold = 1E-30, minus_threshold = 1E-30, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "subiculum APPPS1.il12b-/- vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,160), plus_threshold = 1E-30, minus_threshold = 1E-20, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```  

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("subiculum"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("Thy1", "Negr1", "Il12b", "Pttg1", "Erbb4", "Cdh4", "Dpyd", "Ano1", "Prdm16", "Ube3a", "Cpa6", "Fgf1"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Cdh4", "Il12b","Pttg1", "Erbb4", "Ankfn1", "Kcnc2", "Glra3", "Kcnh8", "Peg3"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("Il12b","Pttg1", "Thy1", "Sntb1", "Stard5", "Ube3a", "Unc13c", "Gm15261"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 subiculum WT samples", ylabel = "log2 average CPM + 1 subiculum APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 subiculum APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 subiculum APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 subiculum WT samples", ylabel = "log2 average CPM + 1 subiculum APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```


### 10. Inhibitory Neurons

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Inhibitory_Neurons_AD_Ctrl.csv", row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Inhibitory Neurons APPPS1 vs WT", x_lim = c(-1, 1), y_lim = c(0,50), plus_threshold = 1E-10, minus_threshold = 1E-10, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Inhibitory_Neurons_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Inhibitory Neurons APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1, 1.5), y_lim = c(0,60), plus_threshold = 1E-10, minus_threshold = 1E-10, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/Inhibitory_Neurons_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Inhibitory Neurons APPPS1.il12b-/- vs WT", x_lim = c(-1, 1.5), y_lim = c(0,80), plus_threshold = 1E-15, minus_threshold = 1E-15, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```  

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Inhibitory Neurons APPPS1 vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,80), plus_threshold = 1E-10, minus_threshold = 1E-10, plus_force = 5, minus_force = 20)
v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Inhibitory Neurons APPPS1 vs APPPS1.il12b-/-", x_lim = c(-1.5, 1.5), y_lim = c(0,80), plus_threshold = 1E-10, minus_threshold = 1E-10, minus_force = 20)
v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Inhibitory Neurons APPPS1.il12b-/- vs WT", x_lim = c(-1.5, 1.5), y_lim = c(0,80), plus_threshold = 1E-15, minus_threshold = 1E-15, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
Seurat_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Inhibitory_Neurons"))

cpm_final <- CPM_calculation(Seurat_sub.SO)

cpm_final_sub1 <- cpm_final[rownames(cpm_final) %in% c("Thy1", "Rsrp1", "Il12b", "Pttg1"), ]
cpm_final_sub2 <- cpm_final[rownames(cpm_final) %in% c("Gm26854", "Il12b","Pttg1", "Peg3"), ]
cpm_final_sub3 <- cpm_final[rownames(cpm_final) %in% c("Il12b","Pttg1", "Thy1", "Gm26854"), ]


s1 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "AD", xlabel = "log2 average CPM + 1 Inhibitory Neurons WT samples", ylabel = "log2 average CPM + 1 Inhibitory Neurons APPPS1 ", cpm_final_sub = cpm_final_sub1)
s2 <- scatter_plot(cpm_final, x_axis = "ADp40KO", y_axis = "AD", xlabel = "log2 average CPM + 1 Inhibitory Neurons APPPS1.il12b-/- samples", ylabel = "log2 average CPM + 1 Inhibitory Neurons APPPS1 ", cpm_final_sub = cpm_final_sub2)
s3 <- scatter_plot(cpm_final, x_axis = "WT", y_axis = "ADp40KO", xlabel = "log2 average CPM + 1 Inhibitory Neurons WT samples", ylabel = "log2 average CPM + 1 Inhibitory Neurons APPPS1.il12b-/- ", cpm_final_sub = cpm_final_sub3)

grid.arrange(s1, s2, s3, ncol = 3)

```

### 11. cluster 29

```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
AD_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cluster/20200721_edgeR_DE_test_clster29_cluster29_AD_Ctrl.csv", row.names = 1)

AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = "Cluster 29 APPPS1 vs WT", x_lim = c(-2, 2), y_lim = c(0,10), plus_threshold = 1E-4, minus_threshold = 1E-4, plus_force = 5, minus_force = 20)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cluster/20200721_edgeR_DE_test_clster29_cluster29_AD_ADp40KO.csv", row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = "Cluster 29 APPPS1 vs APPPS1.il12b-/-", x_lim = c(-2, 2), y_lim = c(0,10), plus_threshold = 1E-2, minus_threshold = 1E-2, minus_force = 20)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cluster/20200721_edgeR_DE_test_clster29_cluster29_ADp40KO_Ctrl.csv", row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = "Cluster 29 APPPS1.il12b-/- vs WT", x_lim = c(-1, 1.5), y_lim = c(0,10), plus_threshold = 1E-3, minus_threshold = 1E-3, minus_force = 10)

grid.arrange(v1, v2, v3, ncol = 3)

```  


```{r warning=FALSE, message=FALSE, fig.width=18, fig.height=5}
sessionInfo()
```


