---
title: "Il12b Vlnplot"
author: "Skim"
date: '2020 10 7 '
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float: false
    code_folding: hide
---

```{r warning=FALSE, message=FALSE, fig.height=8, fig.width=10}
library(Seurat)
library(gridExtra)
library(dplyr)
library(gridExtra)
library(ggplot2)
```

```{r warning=FALSE, message=FALSE, fig.height=10, fig.width=12}
load(file="/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/20200210_figures_for_meeting_report_cleaned_Seurat_object_res0.8.Robj")


```

```{r warning=FALSE, message=FALSE, fig.height=10, fig.width=12}
meta.df <- data9set_cleaned.SO@meta.data %>% mutate(cell_type = case_when(seurat_clusters %in% c(0, 10) ~ "Dentate_Gyrus",
                                                                                             seurat_clusters %in% c(2, 13, 18, 40) ~ "CA1",
                                                                                             seurat_clusters %in% c(9, 21, 27, 32) ~ "CA2_3",
                                                                                             seurat_clusters %in% c(11, 14, 15, 17, 19, 20) ~ "subiculum",
                                                                                             seurat_clusters %in% c(24, 29) ~ "Unidentified_Neurons",
                                                                                             seurat_clusters %in% c(7, 16, 22, 30) ~ "Inhibitory_Neurons",
                                                                                             seurat_clusters %in% c(6) ~ "MOL",
                                                                                             seurat_clusters %in% c(1, 5) ~ "MFOL",
                                                                                             seurat_clusters %in% c(12) ~ "NFOL",
                                                                                             seurat_clusters %in% c(38) ~ "OPC",
                                                                                             seurat_clusters %in% c(3, 8) ~ "Microglia",
                                                                                             seurat_clusters %in% c(4) ~ "Astrocytes",
                                                                                             seurat_clusters %in% c(36) ~ "Vascular",
                                                                                             seurat_clusters %in% c(39) ~ "VLMC",
                                                                                             seurat_clusters %in% c(26) ~ "Choroid",
                                                                                             seurat_clusters %in% c(23) ~ "Fibroblast",
                                                                                             seurat_clusters %in% c(28) ~ "Cajal",
                                                                                             seurat_clusters %in% c(35) ~ "Pericyte",
                                                                                             seurat_clusters %in% c(37) ~ "Macrophage"))


data9set_cleaned.SO$cell_type <- meta.df$cell_type

# give levels to large cell type
data9set_cleaned.SO$cell_type <- factor(data9set_cleaned.SO$cell_type, levels = c("Dentate_Gyrus", "CA1", "CA2_3", "subiculum",  "Unidentified_Neurons", 
                                                                                  "Inhibitory_Neurons", "MOL", "MFOL", "OPC", "NFOL", "Microglia","Astrocytes",
                                                                                  "Vascular", "VLMC", "Choroid", "Fibroblast", "Cajal", "Pericyte", "Macrophage"))

```

```{r warning=FALSE, message=FALSE, fig.height=10, fig.width=12}
data9set_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Dentate_Gyrus","subiculum","CA1", "CA2_3","Unidentified_Neurons"))

data9set_sub.SO <- subset(data9set_sub.SO, subset = sample %in% c("AD"))

EX_Il12b <- data9set_sub.SO@assays$RNA@data[rownames(data9set_sub.SO@assays$RNA@data) %in% "Il12b", ] %>% as.data.frame
colnames(EX_Il12b) <- "Il12b"
EX_Il12b$celltype <- "EX"
```


```{r warning=FALSE, message=FALSE, fig.height=10, fig.width=12}
data9set_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Inhibitory_Neurons"))

data9set_sub.SO <- subset(data9set_sub.SO, subset = sample %in% c("AD"))

IN_Il12b <- data9set_sub.SO@assays$RNA@data[rownames(data9set_sub.SO@assays$RNA@data) %in% "Il12b", ] %>% as.data.frame
colnames(IN_Il12b) <- "Il12b"
IN_Il12b$celltype <- "IN"
```


```{r warning=FALSE, message=FALSE, fig.height=10, fig.width=12}
data9set_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("MOL", "MFOL"))

data9set_sub.SO <- subset(data9set_sub.SO, subset = sample %in% c("AD"))

OL_Il12b <- data9set_sub.SO@assays$RNA@data[rownames(data9set_sub.SO@assays$RNA@data) %in% "Il12b", ] %>% as.data.frame
colnames(OL_Il12b) <- "Il12b"
OL_Il12b$celltype <- "OL"

```

```{r warning=FALSE, message=FALSE, fig.height=10, fig.width=12}
data9set_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("OPC", "NFOL"))

data9set_sub.SO <- subset(data9set_sub.SO, subset = sample %in% c("AD"))

OPC_Il12b <- data9set_sub.SO@assays$RNA@data[rownames(data9set_sub.SO@assays$RNA@data) %in% "Il12b", ] %>% as.data.frame
colnames(OPC_Il12b) <- "Il12b"
OPC_Il12b$celltype <- "OPC"

```


```{r warning=FALSE, message=FALSE, fig.height=10, fig.width=12}
data9set_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Microglia"))

data9set_sub.SO <- subset(data9set_sub.SO, subset = sample %in% c("AD"))

MG_Il12b <- data9set_sub.SO@assays$RNA@data[rownames(data9set_sub.SO@assays$RNA@data) %in% "Il12b", ] %>% as.data.frame
colnames(MG_Il12b) <- "Il12b"
MG_Il12b$celltype <- "MG"

```

```{r warning=FALSE, message=FALSE, fig.height=10, fig.width=12}
data9set_sub.SO <- subset(data9set_cleaned.SO, subset = cell_type %in% c("Astrocytes"))

data9set_sub.SO <- subset(data9set_sub.SO, subset = sample %in% c("AD"))

AS_Il12b <- data9set_sub.SO@assays$RNA@data[rownames(data9set_sub.SO@assays$RNA@data) %in% "Il12b", ] %>% as.data.frame
colnames(AS_Il12b) <- "Il12b"
AS_Il12b$celltype <- "AS"

```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=10}
Il12b <- rbind(EX_Il12b, IN_Il12b, OL_Il12b, OPC_Il12b, MG_Il12b, AS_Il12b)



ggplot(Il12b, aes(x=celltype, y=Il12b, color=celltype)) + 
  geom_violin(trim=FALSE) + 
  geom_jitter(position=position_jitter(0.2), size = 0.3, alpha = 0.3) + ggtitle("Il12b normalized counts including zero counts") +
  geom_text(x=1, y=3.6, label=paste0("express: ", sum(AS_Il12b$Il12b > 0), " / total: ", nrow(AS_Il12b)), size = 3) +
  geom_text(x=2, y=3.6, label=paste0("express: ", sum(EX_Il12b$Il12b > 0), " / total: ", nrow(EX_Il12b)), size = 3) +
  geom_text(x=3, y=3.6, label=paste0("express: ", sum(IN_Il12b$Il12b > 0), " / total: ", nrow(IN_Il12b)), size = 3) +
  geom_text(x=4, y=3.6, label=paste0("express: ", sum(MG_Il12b$Il12b > 0), " / total: ", nrow(MG_Il12b)), size = 3) +
  geom_text(x=5, y=3.6, label=paste0("express: ", sum(OL_Il12b$Il12b > 0), " / total: ", nrow(OL_Il12b)), size = 3) +
  geom_text(x=6, y=3.6, label=paste0("express: ", sum(OPC_Il12b$Il12b > 0), " / total: ", nrow(OPC_Il12b)), size = 3) +
  theme(legend.position = "none")
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=8}
Il12b2 <- Il12b[Il12b$Il12b != 0, ]

ggplot(Il12b2, aes(x=celltype, y=Il12b, color=celltype)) + 
  geom_violin(trim=FALSE) + 
  geom_jitter(position=position_jitter(0.2), size = 0.3, alpha = 0.3) + ggtitle("Il12b normalized counts excluding zero counts") 
```

```{r warning=FALSE, message=FALSE, fig.height=8, fig.width=10}
sessionInfo()
```