---
title: "TF DE genes per cell type"
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float: false
    code_folding: hide
---

This report is to check TF genes from DE analysis by cell type. 

```{r warning=FALSE, message=FALSE}
library(gridExtra)
library(dplyr)
library(ggplot2)
library(tidyr)
library(Seurat, lib.loc = "/data/rajewsky/home/skim/R/")
library(ggrepel)

TF_list <- read.csv("/data/rajewsky/projects/cdr1as_ko_snRNA/3rd_sequencing_run/pyscenic/Mouse_TFs_list.txt", stringsAsFactors = FALSE)
TF_list[725,1] <- "Auts2"
colnames(TF_list) <- "TF"
```

```{r warning=FALSE, message=FALSE}
volcano_plot <- function(DE.df, DE.df_plus, DE.df_minus, DE.df_il12, title = "title", y_lim = c(0,20), x_lim = c(-1, 1), plus_threshold = 1E-5, minus_threshold = 1E-5, plus_force = 10, minus_force = 10){
  ggplot(DE.df) + geom_point(aes(x = logFC, y = -log10(FDR)), shape = 1, alpha = 0.5) +
  geom_point(data = DE.df_plus, aes(x = logFC, y = -log10(FDR)), color = "red", shape = 1, alpha = 0.5) +
  geom_point(data = DE.df_minus, aes(x = logFC, y = -log10(FDR)), color = "blue", shape = 1, alpha = 0.5) +
  geom_point(data = DE.df_plus[DE.df_plus$TF %in% TRUE, ], aes(x = logFC, y = -log10(FDR)), color = "red", shape = 17, size = 2) +
  geom_point(data = DE.df_minus[DE.df_minus$TF %in% TRUE, ], aes(x = logFC, y = -log10(FDR)), color = "blue", shape = 17, size = 2) +
  ggtitle(title) + 
  theme_classic() + 
  xlab("log fold change") + 
  ylab("-log10(adjusted p-value)") +
  scale_y_continuous(expand = c(0,0), limits = y_lim) + xlim(x_lim) + 
  theme(legend.position = "none",
        plot.title = element_text(size = 15, hjust = 0.5, family = "helvetica"),
        axis.title = element_text(size = 15), 
        axis.text = element_text(size = 12, color = "black")) +
  geom_text_repel(data = DE.df_plus[DE.df_plus$FDR < plus_threshold, ], aes(x = logFC, y = -log10(FDR)), label = DE.df_plus[DE.df_plus$FDR < plus_threshold, ]$gene, force = plus_force) + 
  geom_text_repel(data = DE.df_minus[DE.df_minus$FDR < minus_threshold, ], aes(x = logFC, y = -log10(FDR)), label = DE.df_minus[DE.df_minus$FDR < minus_threshold, ]$gene, force = minus_force) + 
  geom_text_repel(data = DE.df_il12, aes(x = logFC, y = -log10(FDR)), label = DE.df_il12$gene)
  
}

volcano_plot_TF_label <- function(DE.df, DE.df_plus, DE.df_minus, DE.df_il12, title = "title", y_lim = c(0,20), x_lim = c(-1, 1), plus_threshold = 1E-5, minus_threshold = 1E-5, plus_force = 10, minus_force = 10){
  ggplot(DE.df) + geom_point(aes(x = logFC, y = -log10(FDR)), shape = 1, alpha = 0.5) +
  geom_point(data = DE.df_plus, aes(x = logFC, y = -log10(FDR)), color = "red", shape = 1, alpha = 0.5) +
  geom_point(data = DE.df_minus, aes(x = logFC, y = -log10(FDR)), color = "blue", shape = 1, alpha = 0.5) +
  geom_point(data = DE.df_plus[DE.df_plus$TF %in% TRUE, ], aes(x = logFC, y = -log10(FDR)), color = "red", shape = 17, size = 2) +
  geom_point(data = DE.df_minus[DE.df_minus$TF %in% TRUE, ], aes(x = logFC, y = -log10(FDR)), color = "blue", shape = 17, size = 2) +
  ggtitle(title) + 
  theme_classic() + 
  xlab("log fold change") + 
  ylab("-log10(adjusted p-value)") +
  scale_y_continuous(expand = c(0,0), limits = y_lim) + xlim(x_lim) + 
  theme(legend.position = "none",
        plot.title = element_text(size = 15, hjust = 0.5, family = "helvetica"),
        axis.title = element_text(size = 15), 
        axis.text = element_text(size = 12, color = "black")) +
  geom_text_repel(data = DE.df_plus[DE.df_plus$TF %in% TRUE, ], aes(x = logFC, y = -log10(FDR)), label = DE.df_plus[DE.df_plus$TF %in% TRUE, ]$gene, force = plus_force) + 
  geom_text_repel(data = DE.df_minus[DE.df_minus$TF %in% TRUE, ], aes(x = logFC, y = -log10(FDR)), label = DE.df_minus[DE.df_minus$TF %in% TRUE, ]$gene, force = minus_force) + 
  geom_text_repel(data = DE.df_il12, aes(x = logFC, y = -log10(FDR)), label = DE.df_il12$gene)
  
}

comb_fig <- function(Cell_type = "MOL", y_lim_value = c(0,20), x_lim_value = c(-1, 1)){
  
  AD_Ctrl.df <- read.csv(paste0("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/",Cell_type,"_AD_Ctrl.csv"), row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]
AD_Ctrl.df$TF <- AD_Ctrl.df$gene %in% TF_list$TF

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = paste0(Cell_type, " APPPS1 vs WT"), minus_force = 20, y_lim = y_lim_value, x_lim = x_lim_value)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv(paste0("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/",Cell_type,"_AD_ADp40KO.csv"), row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]
AD_ADp40KO.df$TF <- AD_ADp40KO.df$gene %in% TF_list$TF

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = paste0(Cell_type," APPPS1 vs APPPS1.il12b-/-"), minus_force = 20, y_lim = y_lim_value, x_lim = x_lim_value)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv(paste0("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/",Cell_type,"_ADp40KO_Ctrl.csv"), row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]
ADp40KO_Ctrl.df$TF <- ADp40KO_Ctrl.df$gene %in% TF_list$TF

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = paste0(Cell_type," APPPS1.il12b-/- vs WT"), plus_threshold = 1E-7, minus_threshold = 1E-7, minus_force = 20, y_lim = y_lim_value, x_lim = x_lim_value)

grid.arrange(v1, v2, v3, ncol = 3)
}


comb_fig_TF <- function(Cell_type = "MOL", y_lim = c(0,20), x_lim = c(-1, 1)){
  
  AD_Ctrl.df <- read.csv(paste0("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/",Cell_type,"_AD_Ctrl.csv"), row.names = 1)
AD_Ctrl.df <- AD_Ctrl.df[AD_Ctrl.df$gene != "Ttr", ]
AD_Ctrl.df$TF <- AD_Ctrl.df$gene %in% TF_list$TF

AD_Ctrl_plus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC > 0.25), ]
AD_Ctrl_minus.df <- AD_Ctrl.df[which(AD_Ctrl.df$FDR < 0.01 & AD_Ctrl.df$logFC < -0.25), ]
AD_Ctrl_il12b.df <- AD_Ctrl.df[which(AD_Ctrl.df$gene == "Il12b"), ]

v1 <- volcano_plot_TF_label(AD_Ctrl.df, AD_Ctrl_plus.df, AD_Ctrl_minus.df, AD_Ctrl_il12b.df, title = paste0(Cell_type," APPPS1 vs WT"), minus_force = 20, y_lim = y_lim, x_lim = x_lim)

# AD vs ADp40KO
AD_ADp40KO.df <- read.csv(paste0("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/",Cell_type,"_AD_ADp40KO.csv"), row.names = 1)
AD_ADp40KO.df <- AD_ADp40KO.df[AD_ADp40KO.df$gene != "Ttr", ]
AD_ADp40KO.df$TF <- AD_ADp40KO.df$gene %in% TF_list$TF

AD_ADp40KO_plus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC > 0.25), ]
AD_ADp40KO_minus.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$FDR < 0.01 & AD_ADp40KO.df$logFC < -0.25), ]
AD_ADp40KO_il12b.df <- AD_ADp40KO.df[which(AD_ADp40KO.df$gene == "Il12b"), ]

v2 <- volcano_plot_TF_label(AD_ADp40KO.df, AD_ADp40KO_plus.df, AD_ADp40KO_minus.df, AD_ADp40KO_il12b.df, title = paste0(Cell_type," APPPS1 vs APPPS1.il12b-/-"), minus_force = 20, y_lim = y_lim, x_lim = x_lim)


# ADp40KO vs Ctrl
ADp40KO_Ctrl.df <- read.csv(paste0("/data/rajewsky/home/skim/Microglia_Heppner/201912_10X_9sets/R_Scripts/DE_csv_files/edgeR/cell_type/",Cell_type,"_ADp40KO_Ctrl.csv"), row.names = 1)
ADp40KO_Ctrl.df <- ADp40KO_Ctrl.df[ADp40KO_Ctrl.df$gene != "Ttr", ]
ADp40KO_Ctrl.df$TF <- ADp40KO_Ctrl.df$gene %in% TF_list$TF

ADp40KO_Ctrl_plus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC > 0.25), ]
ADp40KO_Ctrl_minus.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$FDR < 0.01 & ADp40KO_Ctrl.df$logFC < -0.25), ]
ADp40KO_Ctrl_il12b.df <- ADp40KO_Ctrl.df[which(ADp40KO_Ctrl.df$gene == "Il12b"), ]

v3 <- volcano_plot_TF_label(ADp40KO_Ctrl.df, ADp40KO_Ctrl_plus.df, ADp40KO_Ctrl_minus.df, ADp40KO_Ctrl_il12b.df, title = paste0(Cell_type," APPPS1.il12b-/- vs WT"), plus_threshold = 1E-7, minus_threshold = 1E-7, minus_force = 20, y_lim = y_lim, x_lim = x_lim)

grid.arrange(v1, v2, v3, ncol = 3)
}

```

### 1. MOL

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "MOL")
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}
comb_fig_TF(Cell_type = "MOL")
```

### 2. MFOL

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "MFOL", y_lim = c(0,80), x_lim = c(-1.2,1.2))
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "MFOL", y_lim = c(0,80), x_lim = c(-1.2,1.2))
```

### 3. OPC

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "OPC", y_lim = c(0,20), x_lim = c(-1.2,1.2))
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "OPC", y_lim = c(0,20), x_lim = c(-1.2,1.2))
```

### 4. Astrocytes

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "Astrocytes", y_lim = c(0,40), x_lim = c(-1.2,1.2))
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "Astrocytes", y_lim = c(0,40), x_lim = c(-1.2,1.2))
```

### 5. Microglia

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "Microglia", y_lim = c(0,150), x_lim = c(-3,3))
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "Microglia", y_lim = c(0,150), x_lim = c(-3,3))
```

### 6. Dentate_Gyrus

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "Dentate_Gyrus", y_lim = c(0,120), x_lim = c(-1.2,1.2))
```


```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "Dentate_Gyrus", y_lim = c(0,120), x_lim = c(-1.2,1.2))
```

### 7. CA1

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "CA1", y_lim = c(0,120), x_lim = c(-1.2,1.2))
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "CA1", y_lim = c(0,120), x_lim = c(-1.2,1.2))
```

### 8. CA2/3

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "CA2_3", y_lim = c(0,50), x_lim = c(-1.2,1.2))
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "CA2_3", y_lim = c(0,50), x_lim = c(-1.2,1.2))
```

### 9. subiculum

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "subiculum", y_lim = c(0,70), x_lim = c(-1.2,1.2))
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "subiculum", y_lim = c(0,70), x_lim = c(-1.2,1.2))
```

### 10. Inhibitory_Neurons

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig(Cell_type = "Inhibitory_Neurons", y_lim = c(0,60), x_lim = c(-1.2,1.2))
```

```{r warning=FALSE, message=FALSE, fig.height=5, fig.width=15}

comb_fig_TF(Cell_type = "Inhibitory_Neurons", y_lim = c(0,60), x_lim = c(-1.2,1.2))
```

```{r warning=FALSE, message=FALSE}

```

```{r warning=FALSE, message=FALSE}

```

```{r warning=FALSE, message=FALSE}

```

```{r warning=FALSE, message=FALSE}

```

```{r warning=FALSE, message=FALSE}

```

```{r warning=FALSE, message=FALSE}

```

```{r warning=FALSE, message=FALSE}
sessionInfo()
```